env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - standard
  - 'plugin:react-hooks/recommended'
  - 'plugin:@next/next/recommended'
  - 'plugin:jsx-a11y/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
globals:
  React: true
rules:
  indent:
    - error
    - tab
  no-tabs:
    - off
  quotes:
    - error
    - backtick
  react/jsx-uses-react:
    - off
  react/react-in-jsx-scope:
    - off
